/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XSLT
 #	author : miyako
 #	2016/09/20
 #
 # --------------------------------------------------------------------------------*/

#include <libxml/xmlmemory.h>
#include <libxml/debugXML.h>
#include <libxml/HTMLtree.h>
#include <libxml/xmlIO.h>
#include <libxml/parser.h>
#include <libxml/xinclude.h>
#include <libxml/catalog.h>

#include <libxslt/xslt.h>
#include <libxslt/xsltInternals.h>
#include <libxslt/transform.h>
#include <libxslt/xsltutils.h>
#include <libxslt/security.h>
#include <libexslt/exslt.h>

// --- XSLT
void XSLT_Apply_stylesheet(sLONG_PTR *pResult, PackagePtr pParams);
void XSLT_Apply_stylesheet_data(sLONG_PTR *pResult, PackagePtr pParams);
