/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XSLT
 #	author : miyako
 #	2014/08/13
 #
 # --------------------------------------------------------------------------------*/



// --- XSLT
void XSLT_Apply_stylesheet(sLONG_PTR *pResult, PackagePtr pParams);
